### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by localredhead** [uport-project/uport-project.github.io#23]
After configuring Algolia please install the JS snippet. 

Modify `header.jsx` so that the search bar is between the uport logo and `overview`
![Screen Shot 2018-05-22 at 11.00.58 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5670e3274b7b6413000155b3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f16b7191a379ee0c2b51415a46bc21254d58eeb9cb74fce36f34985619e8836d5b77976f13aab9854aba50ba208a1cd4e5eadb48c0fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e64d51a0143565e572366e0a.png)

We'll want to confirm with @jahowle on the placement, but lets get the MVP in place first.

**Comment by gbugyis** [comment]
@jahowle - This is the doc search one I mentioned yesterday. Feedback can go here whenever you have a chance to look at it.
