### ISSUE TITLE
Error in javascript console when using mac Safari

### ISSUE THREAD

**Issue by localredhead** [uport-project/uport-project.github.io#33]
I am unable to reproduce the error shown in the attached screenshot

![Screen Shot 2018-06-01 at 1.04.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5670e3274b7b6413000155b3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f26b7191a379f1122f4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ebfd1695c25943f17adbfd71aee01ba21d81ed6e0ed8e4cd2f42f67b6d5db1063474f4dcbed5727a19041c95df44ce94554ac1b3460ee742431.png)

The same user reported that firefox on the same machine did not display this issue.     Safari is unusable in this state.

**Comment by gbugyis** [comment]
Closing - just a CDN/caching issue. User reported as fixed.
