### ISSUE TITLE
Multiple keys creating warning

### ISSUE THREAD

**Issue by jrgleason** [uport-project/uport-project.github.io#43]
In Navigation.jsx line 96ish you see the following...

    <StyledLink
                className={`w-nav-link nav-link menu-item ${this.props.activeCategory === section ? 'active' : ''}`}
                to={`${page.node.fields.slug}`}
                activeClassName="active"
                key={section}
    >

Problem here is if section is the same for 2 pages. An example of this in the demo is tutorial. Then in the client it throws the following exception.

> index.js:2177 Warning: Encountered two children with the same key, `tutorials`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

So we need to find a new property for the key. This works but I am not sure how it affects other things.

    key={`${page.node.fields.slug}`}

**Comment by localredhead** [comment]
https://github.com/uport-project/uport-project.github.io/pull/61/commits/f918958d2323b40fc2742b24f9777296b1290f45
